# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lge/geant4/hybrid_spect_lge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lge/geant4/hybrid_spect_lge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lge/geant4/hybrid_spect_lge/CMakeFiles /home/lge/geant4/hybrid_spect_lge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lge/geant4/hybrid_spect_lge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lacc_quad

# Build rule for target.
lacc_quad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lacc_quad
.PHONY : lacc_quad

# fast build rule for target.
lacc_quad/fast:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/build
.PHONY : lacc_quad/fast

lacc_quad.o: lacc_quad.cc.o

.PHONY : lacc_quad.o

# target to build an object file
lacc_quad.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/lacc_quad.cc.o
.PHONY : lacc_quad.cc.o

lacc_quad.i: lacc_quad.cc.i

.PHONY : lacc_quad.i

# target to preprocess a source file
lacc_quad.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/lacc_quad.cc.i
.PHONY : lacc_quad.cc.i

lacc_quad.s: lacc_quad.cc.s

.PHONY : lacc_quad.s

# target to generate assembly for a file
lacc_quad.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/lacc_quad.cc.s
.PHONY : lacc_quad.cc.s

src/ActionInitialization.o: src/ActionInitialization.cc.o

.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i

.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s

.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/CCEventAction.o: src/CCEventAction.cc.o

.PHONY : src/CCEventAction.o

# target to build an object file
src/CCEventAction.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/CCEventAction.cc.o
.PHONY : src/CCEventAction.cc.o

src/CCEventAction.i: src/CCEventAction.cc.i

.PHONY : src/CCEventAction.i

# target to preprocess a source file
src/CCEventAction.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/CCEventAction.cc.i
.PHONY : src/CCEventAction.cc.i

src/CCEventAction.s: src/CCEventAction.cc.s

.PHONY : src/CCEventAction.s

# target to generate assembly for a file
src/CCEventAction.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/CCEventAction.cc.s
.PHONY : src/CCEventAction.cc.s

src/CCRunAction.o: src/CCRunAction.cc.o

.PHONY : src/CCRunAction.o

# target to build an object file
src/CCRunAction.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/CCRunAction.cc.o
.PHONY : src/CCRunAction.cc.o

src/CCRunAction.i: src/CCRunAction.cc.i

.PHONY : src/CCRunAction.i

# target to preprocess a source file
src/CCRunAction.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/CCRunAction.cc.i
.PHONY : src/CCRunAction.cc.i

src/CCRunAction.s: src/CCRunAction.cc.s

.PHONY : src/CCRunAction.s

# target to generate assembly for a file
src/CCRunAction.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/CCRunAction.cc.s
.PHONY : src/CCRunAction.cc.s

src/DEPosHit.o: src/DEPosHit.cc.o

.PHONY : src/DEPosHit.o

# target to build an object file
src/DEPosHit.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DEPosHit.cc.o
.PHONY : src/DEPosHit.cc.o

src/DEPosHit.i: src/DEPosHit.cc.i

.PHONY : src/DEPosHit.i

# target to preprocess a source file
src/DEPosHit.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DEPosHit.cc.i
.PHONY : src/DEPosHit.cc.i

src/DEPosHit.s: src/DEPosHit.cc.s

.PHONY : src/DEPosHit.s

# target to generate assembly for a file
src/DEPosHit.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DEPosHit.cc.s
.PHONY : src/DEPosHit.cc.s

src/DEPosSD.o: src/DEPosSD.cc.o

.PHONY : src/DEPosSD.o

# target to build an object file
src/DEPosSD.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DEPosSD.cc.o
.PHONY : src/DEPosSD.cc.o

src/DEPosSD.i: src/DEPosSD.cc.i

.PHONY : src/DEPosSD.i

# target to preprocess a source file
src/DEPosSD.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DEPosSD.cc.i
.PHONY : src/DEPosSD.cc.i

src/DEPosSD.s: src/DEPosSD.cc.s

.PHONY : src/DEPosSD.s

# target to generate assembly for a file
src/DEPosSD.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DEPosSD.cc.s
.PHONY : src/DEPosSD.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/LacaDesignFactor.o: src/LacaDesignFactor.cc.o

.PHONY : src/LacaDesignFactor.o

# target to build an object file
src/LacaDesignFactor.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/LacaDesignFactor.cc.o
.PHONY : src/LacaDesignFactor.cc.o

src/LacaDesignFactor.i: src/LacaDesignFactor.cc.i

.PHONY : src/LacaDesignFactor.i

# target to preprocess a source file
src/LacaDesignFactor.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/LacaDesignFactor.cc.i
.PHONY : src/LacaDesignFactor.cc.i

src/LacaDesignFactor.s: src/LacaDesignFactor.cc.s

.PHONY : src/LacaDesignFactor.s

# target to generate assembly for a file
src/LacaDesignFactor.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/LacaDesignFactor.cc.s
.PHONY : src/LacaDesignFactor.cc.s

src/MaskParam.o: src/MaskParam.cc.o

.PHONY : src/MaskParam.o

# target to build an object file
src/MaskParam.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/MaskParam.cc.o
.PHONY : src/MaskParam.cc.o

src/MaskParam.i: src/MaskParam.cc.i

.PHONY : src/MaskParam.i

# target to preprocess a source file
src/MaskParam.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/MaskParam.cc.i
.PHONY : src/MaskParam.cc.i

src/MaskParam.s: src/MaskParam.cc.s

.PHONY : src/MaskParam.s

# target to generate assembly for a file
src/MaskParam.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/MaskParam.cc.s
.PHONY : src/MaskParam.cc.s

src/PhotCntHit.o: src/PhotCntHit.cc.o

.PHONY : src/PhotCntHit.o

# target to build an object file
src/PhotCntHit.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhotCntHit.cc.o
.PHONY : src/PhotCntHit.cc.o

src/PhotCntHit.i: src/PhotCntHit.cc.i

.PHONY : src/PhotCntHit.i

# target to preprocess a source file
src/PhotCntHit.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhotCntHit.cc.i
.PHONY : src/PhotCntHit.cc.i

src/PhotCntHit.s: src/PhotCntHit.cc.s

.PHONY : src/PhotCntHit.s

# target to generate assembly for a file
src/PhotCntHit.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhotCntHit.cc.s
.PHONY : src/PhotCntHit.cc.s

src/PhotCntSD.o: src/PhotCntSD.cc.o

.PHONY : src/PhotCntSD.o

# target to build an object file
src/PhotCntSD.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhotCntSD.cc.o
.PHONY : src/PhotCntSD.cc.o

src/PhotCntSD.i: src/PhotCntSD.cc.i

.PHONY : src/PhotCntSD.i

# target to preprocess a source file
src/PhotCntSD.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhotCntSD.cc.i
.PHONY : src/PhotCntSD.cc.i

src/PhotCntSD.s: src/PhotCntSD.cc.s

.PHONY : src/PhotCntSD.s

# target to generate assembly for a file
src/PhotCntSD.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhotCntSD.cc.s
.PHONY : src/PhotCntSD.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

src/PrimaryGeneratorAction_GPS.o: src/PrimaryGeneratorAction_GPS.cc.o

.PHONY : src/PrimaryGeneratorAction_GPS.o

# target to build an object file
src/PrimaryGeneratorAction_GPS.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PrimaryGeneratorAction_GPS.cc.o
.PHONY : src/PrimaryGeneratorAction_GPS.cc.o

src/PrimaryGeneratorAction_GPS.i: src/PrimaryGeneratorAction_GPS.cc.i

.PHONY : src/PrimaryGeneratorAction_GPS.i

# target to preprocess a source file
src/PrimaryGeneratorAction_GPS.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PrimaryGeneratorAction_GPS.cc.i
.PHONY : src/PrimaryGeneratorAction_GPS.cc.i

src/PrimaryGeneratorAction_GPS.s: src/PrimaryGeneratorAction_GPS.cc.s

.PHONY : src/PrimaryGeneratorAction_GPS.s

# target to generate assembly for a file
src/PrimaryGeneratorAction_GPS.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PrimaryGeneratorAction_GPS.cc.s
.PHONY : src/PrimaryGeneratorAction_GPS.cc.s

src/PrimaryGeneratorAction_PG.o: src/PrimaryGeneratorAction_PG.cc.o

.PHONY : src/PrimaryGeneratorAction_PG.o

# target to build an object file
src/PrimaryGeneratorAction_PG.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PrimaryGeneratorAction_PG.cc.o
.PHONY : src/PrimaryGeneratorAction_PG.cc.o

src/PrimaryGeneratorAction_PG.i: src/PrimaryGeneratorAction_PG.cc.i

.PHONY : src/PrimaryGeneratorAction_PG.i

# target to preprocess a source file
src/PrimaryGeneratorAction_PG.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PrimaryGeneratorAction_PG.cc.i
.PHONY : src/PrimaryGeneratorAction_PG.cc.i

src/PrimaryGeneratorAction_PG.s: src/PrimaryGeneratorAction_PG.cc.s

.PHONY : src/PrimaryGeneratorAction_PG.s

# target to generate assembly for a file
src/PrimaryGeneratorAction_PG.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/PrimaryGeneratorAction_PG.cc.s
.PHONY : src/PrimaryGeneratorAction_PG.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

src/TrackingAction.o: src/TrackingAction.cc.o

.PHONY : src/TrackingAction.o

# target to build an object file
src/TrackingAction.cc.o:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/TrackingAction.cc.o
.PHONY : src/TrackingAction.cc.o

src/TrackingAction.i: src/TrackingAction.cc.i

.PHONY : src/TrackingAction.i

# target to preprocess a source file
src/TrackingAction.cc.i:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/TrackingAction.cc.i
.PHONY : src/TrackingAction.cc.i

src/TrackingAction.s: src/TrackingAction.cc.s

.PHONY : src/TrackingAction.s

# target to generate assembly for a file
src/TrackingAction.cc.s:
	$(MAKE) -f CMakeFiles/lacc_quad.dir/build.make CMakeFiles/lacc_quad.dir/src/TrackingAction.cc.s
.PHONY : src/TrackingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lacc_quad"
	@echo "... lacc_quad.o"
	@echo "... lacc_quad.i"
	@echo "... lacc_quad.s"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/CCEventAction.o"
	@echo "... src/CCEventAction.i"
	@echo "... src/CCEventAction.s"
	@echo "... src/CCRunAction.o"
	@echo "... src/CCRunAction.i"
	@echo "... src/CCRunAction.s"
	@echo "... src/DEPosHit.o"
	@echo "... src/DEPosHit.i"
	@echo "... src/DEPosHit.s"
	@echo "... src/DEPosSD.o"
	@echo "... src/DEPosSD.i"
	@echo "... src/DEPosSD.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/LacaDesignFactor.o"
	@echo "... src/LacaDesignFactor.i"
	@echo "... src/LacaDesignFactor.s"
	@echo "... src/MaskParam.o"
	@echo "... src/MaskParam.i"
	@echo "... src/MaskParam.s"
	@echo "... src/PhotCntHit.o"
	@echo "... src/PhotCntHit.i"
	@echo "... src/PhotCntHit.s"
	@echo "... src/PhotCntSD.o"
	@echo "... src/PhotCntSD.i"
	@echo "... src/PhotCntSD.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
	@echo "... src/PrimaryGeneratorAction_GPS.o"
	@echo "... src/PrimaryGeneratorAction_GPS.i"
	@echo "... src/PrimaryGeneratorAction_GPS.s"
	@echo "... src/PrimaryGeneratorAction_PG.o"
	@echo "... src/PrimaryGeneratorAction_PG.i"
	@echo "... src/PrimaryGeneratorAction_PG.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
	@echo "... src/TrackingAction.o"
	@echo "... src/TrackingAction.i"
	@echo "... src/TrackingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

